import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Qpips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
    <body
  className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen bg-transparent `}
>
  {/* Background Image Layer */}
  <div
    className="absolute inset-0 -z-10 bg-cover bg-center opacity-50"
    style={{
      backgroundImage:
        "url('/5523744.jpg')",
    }}
  />
  

  {children}
</body>

  </html>
)

}
