import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Qpips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ Fully mobile-optimized meta */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no"
        />
        <meta name="format-detection" content="telephone=no" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen bg-transparent overflow-x-hidden`}
        style={{
          WebkitTextSizeAdjust: "100%", // Prevents Chrome text zoom
          textSizeAdjust: "100%",
          overscrollBehavior: "none",
          margin: 0,
          padding: 0,
        }}
      >
        {/* ✅ Optimized background for small screens */}
        <div
          className="fixed inset-0 -z-10 bg-cover bg-center bg-no-repeat opacity-60"
          style={{
            backgroundImage: "url('/5523744.jpg')",
            backgroundSize: "cover",
            backgroundPosition: "center center",
            backgroundAttachment: "scroll", // Better for low-end mobile performance
          }}
        />

        {/* ✅ Main container with adaptive spacing */}
        <main
          className="
            flex flex-col items-center justify-center 
            min-h-screen w-full 
            px-4 sm:px-6 lg:px-8 
            py-6 sm:py-8
            space-y-4 sm:space-y-6
            text-center
          "
        >
          <div className="w-full max-w-[420px] sm:max-w-[640px] mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
